"""Добавление users

Revision ID: 590026fe6b58
Revises: bfa7d9778b2e
Create Date: 2024-06-14 16:29:17.867467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590026fe6b58'
down_revision: Union[str, None] = 'bfa7d9778b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'memes', ['s3_image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memes', type_='unique')
    # ### end Alembic commands ###
