"""Изменение типа поля в таблице Memes

Revision ID: bfa7d9778b2e
Revises: 04f7302ede2e
Create Date: 2024-06-13 18:26:47.609442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa7d9778b2e'
down_revision: Union[str, None] = '04f7302ede2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('s3_image_url', sa.String(), nullable=False))
    op.drop_column('memes', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memes', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('memes', 's3_image_url')
    # ### end Alembic commands ###
